Readme
ikcamp/Functional-Light-JS pull request #41
Opened 2017-06-20 09:09 UTC by MatildaJin

add: readme

2017-06-21 02:36 UTC, blueken commented
校对认领

2017-06-21 03:42 UTC, blueken requested changes

2017-06-21 03:42 UTC, blueken commented on README.md
> +# 轻量函数式编程
全文统一使用轻量级函数式编程， 下面还有两处

2017-06-21 03:42 UTC, blueken commented on README.md
> +**注释：** 题目中使用了“轻量”二字，然而这并不是一本“轻松的”“入门级”书籍。本书是严谨的，充斥着各种复杂的细节，适合拥有扎实 JS 知识基础的阅读者进行研读。“轻量”意味着范围的缩小。通常来说，关于函数式编程的 JavaScript 书籍都热衷于拓展阅读者的知识面，并企图覆盖更多的知识点。而本书则对于每一个话题都进行了深入的探究，尽管这种探究是小范围进行的。
“范围的缩小” 建议-》 “有限的范围”

2017-06-21 03:42 UTC, blueken commented on README.md
> +让我们面对这个事实：除非你已经是函数式编程高手中的一员（至少我不是！），否则类似“一个单元仅仅是自函子中的独异点”这类说法对我们来说毫无意义。
monad -> 单子
monoid -> 幺半群,独异点 一般译成幺半群的多一些

2017-06-21 03:42 UTC, blueken commented on README.md
> +这并不是说，各种复杂繁琐的概念是*无意义*的，更不是说，函数式编程者滥用了它们。一旦你完全掌握了轻量的函数式编程内容，你将会／但愿会想要对函数式编程的各种概念进行更正式更系统的学习，并且你一定会对它们的意义和原因有更深入的理解。
将会／但愿会想要  -》 或许希望 

此处可以不用忠于原文，换取更流畅的阅读

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [第二章：功能函数的基础](ch2.md)
函数式编程函数基础

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [第四章：创建函数](ch4.md)
函数组合

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [第十章：异步功能](ch10.md)
异步函数式编程

2017-06-21 03:42 UTC, blueken commented on README.md
> +本书主要在 [on Leanpub](https://leanpub.com/fljs/) 平台上以电子版本的形式进行出版。我也尝试出售本书的纸质版本，然而仍然没有确实的方案。
然而仍然 -> 但

2017-06-21 03:42 UTC, blueken commented on README.md
> +如果除了购买本书以外，你想要对本书作一些物质上的捐赠，请在 [patreon](https://www.patreon.com/getify) 上进行操作。本书作者感谢你的慷慨解囊。
本书作者感谢你的 -》 我感谢您的

2017-06-21 03:42 UTC, blueken commented on README.md
> +如果你喜欢本书的内容，并希望组织此类课程，或者组织关于其他 JS／HTML5/Node.js 课程，请通过以下方式联系我：
JS／HTML5/Node.js  -》 两个斜线不一样？

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [附录 A ：转换](apA.md)
这个单词技术性太强，是个组合词，原义指使用组合的方式来处理Reduce。
建议不翻译，保留原词即可

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [附录 B ：基础单元](apB.md)
谦虚的 Monad

2017-06-21 03:42 UTC, blueken commented on README.md
> +* [附录 C ：函数式编程代码库](apC.md)
代码库-> 类库

2017-06-21 03:42 UTC, blueken commented on README.md
> +本书所有的材料和内容都归属 (c) 2016-2017 Kyle Simpson 所有。
归属 -》 归

2017-07-11 05:34 UTC, MatildaJin commented
修改完成

2017-08-01 08:20 UTC, lilins commented on README.md
> +这并不是说，各种复杂繁琐的概念是*无意义*的，更不是说，函数式编程者滥用了它们。一旦你完全掌握了轻量的函数式编程内容，你将会／但愿会想要对函数式编程的各种概念进行更正式更系统的学习，并且你一定会对它们的意义和原因有更深入的理解。
*无意义* => **无意义**
英文斜体 翻译成中文需要变成加粗

2017-08-01 08:20 UTC, lilins commented on README.md
> +但是我更想要让你能够*现在*就把一些函数式编程的基础运用到 JavaScript 编程过程中去，因为我相信这会帮助你写出更优秀的，更*符合逻辑*的代码。
*现在* => **现在**
*符合逻辑* => **符合逻辑**
英文斜体 翻译成中文需要变成加粗

2017-08-01 08:20 UTC, lilins commented on README.md
> +**非常欢迎**对于本书的任何内容贡献。但是在提交 PR 之前*请务必*认真阅读 [Contributions Guidelines](CONTRIBUTING.md)。
*请务必* => **请务必**
英文斜体 翻译成中文需要变成加粗

2017-08-03 02:27 UTC, miaodongqing commented on README.md
> +本书主要在 [on Leanpub](https://leanpub.com/fljs/) 平台上以电子版本的形式进行出版。我也尝试出售本书的纸质版本，但没有确实的方案。
建议将
确实的 => 确定的

2017-08-03 02:27 UTC, miaodongqing commented on README.md
> +如果除了购买本书以外，你想要对本书作一些物质上的捐赠，请在 [patreon](https://www.patreon.com/getify) 上进行操作。本书作者感谢你的慷慨解囊。
建议将
如果除了购买本书以外，你想要对本书作一些物质上的捐赠 =》 除了购买本书之外，如果你想要对本书作一些物质上的捐赠

2017-08-03 02:28 UTC, miaodongqing commented
校对完成

2017-08-08 16:08 UTC, yanyixin commented
@MatildaJin  终校完毕，没什么问题

2017-08-14 02:18 UTC, MatildaJin commented
@yanyixin  章节题目加入完毕

2017-08-14 11:36 UTC, merged